package com.appcoins.wallet.core.utils.common

import java.util.concurrent.TimeUnit

class RequestMocks {
  companion object {
    val userStatsPromos = """{
          "promotions": [
          {
            "id": "GAMIFICATION",
            "current_amount": 2938120.58297987,
            "level": 8,
            "bonus": 18,
            "next_level_amount": 3500000,
            "bonus_earned": 452933.50307623664,
            "status": "ACTIVE",
            "bundle": true,
            "user_type": "UNDEFINED",
            "priority": 100,
            "gamification_status": "VIP",
            "approaching_next_level": null
          },
          {
            "id": "PACKAGE_DISTRIBUTION_PERK",
            "priority": 0,
            "start_date": 1658794592,
            "end_date": 1659609034,
            "current_progress": "0",
            "objective_progress": "0",
            "icon": "https://cdn6.aptoide.com/imgs/2/e/7/2e7440a8d6154c3a05e611a44c86296a_icon.png",
            "view_type": "DEFAULT",
            "linked_promotion_id": null,
            "details_link": "https://appcoins-trivial-drive-demo-sample.en.aptoide.com/",
            "app_name": "Appcoins Trivial Drive demo sample",
            "gamification_status": "VIP",
            "notification_title": "New Perk",
            "notification_description": "Receive an extra 5% Bonus in all your purchases, except AppCoins Credits, in Appcoins Trivial Drive demo sample.",
            "perk_description": "Receive an extra 5% Bonus in all your purchases."
          },
          {
            "id": "PACKAGE_DISTRIBUTION_PERK",
            "priority": 0,
            "start_date": 1658737567,
            "end_date": 1669263172,
            "current_progress": "0",
            "objective_progress": "0",
            "icon": "https://cdn6.aptoide.com/imgs/6/c/8/6c8dfb1fa8f2c7a6a8fefccf6976274c.png",
            "view_type": "DEFAULT",
            "linked_promotion_id": null,
            "details_link": "https://appcoins-trivial-drive-demo-sample.en.aptoide.com/",
            "app_name": "Appcoins Trivial Drive demo sample",
            "gamification_status": "STANDARD",
            "notification_title": "New Perk",
            "notification_description": "Receive an extra 5% Bonus in all your purchases, except AppCoins Credits, in Appcoins Trivial Drive demo sample.",
            "perk_description": "Receive an extra 5% Bonus in all your purchases."
          },
          {
            "id": "PROMO_CODE_PERK",
            "priority": 0,
            "start_date": 1658737567,
            "end_date": 1659609034,
            "current_progress": "0",
            "objective_progress": "0",
            "icon": "https://cdn6.aptoide.com/imgs/6/c/8/6c8dfb1fa8f2c7a6a8fefccf6976274c.png",
            "view_type": "DEFAULT",
            "linked_promotion_id": null,
            "details_link": "https://appcoins-trivial-drive-demo-sample.en.aptoide.com/",
            "app_name": "Appcoins Trivial Drive demo sample",
            "gamification_status": "STANDARD",
            "notification_title": "New Perk",
            "notification_description": "Receive an extra 5% Bonus in all your purchases, except AppCoins Credits, in Appcoins Trivial Drive demo sample.",
            "perk_description": "Receive an extra 5% Bonus in all your purchases."
          },
          {
            "id": "PROMO_CODE_PERK",
            "priority": 0,
            "start_date": 1658737567,
            "end_date": 1659609034,
            "current_progress": "0",
            "objective_progress": "0",
            "icon": "https://cdn6.aptoide.com/imgs/6/c/8/6c8dfb1fa8f2c7a6a8fefccf6976274c.png",
            "view_type": "DEFAULT",
            "linked_promotion_id": null,
            "details_link": "https://appcoins-trivial-drive-demo-sample.en.aptoide.com/",
            "app_name": "Appcoins Trivial Drive demo sample",
            "gamification_status": "VIP",
            "notification_title": "New Perk",
            "notification_description": "Receive an extra 5% Bonus in all your purchases, except AppCoins Credits, in Appcoins Trivial Drive demo sample.",
            "perk_description": "Receive an extra 5% Bonus in all your purchases."
          },
          {
            "id": "GAMIFICATION_LEVEL_UP",
            "priority": 32,
            "start_date": 1596672000,
            "end_date": 1669577600,
            "current_progress": "2938120.58",
            "objective_progress": "3500000.0",
            "icon": "https://cdn6.aptoide.com/imgs/2/e/7/2e7440a8d6154c3a05e611a44c86296a_icon.png",
            "view_type": "PROGRESS",
            "linked_promotion_id": "GAMIFICATION",
            "details_link": null,
            "app_name": null,
            "gamification_status": "REGULAR",
            "notification_title": "Earn AppCoins Credits!",
            "notification_description": "Reach the next level and receive 6000 AppCoins Credits!",
            "perk_description": "Reach the next level and receive 6000 AppCoins Credits!"
          },
          {
            "id": "PROMO_CODE_PERK",
            "priority": 0,
            "start_date": 1659708015,
            "end_date": 1659909034,
            "current_progress": "0",
            "objective_progress": "0",
            "icon": "https://cdn6.aptoide.com/imgs/6/c/8/6c8dfb1fa8f2c7a6a8fefccf6976274c.png",
            "view_type": "DEFAULT",
            "linked_promotion_id": null,
            "details_link": "https://appcoins-trivial-drive-demo-sample.en.aptoide.com/",
            "app_name": "Appcoins Trivial Drive demo sample",
            "gamification_status": "VIP",
            "notification_title": "New Perk",
            "notification_description": "Receive an extra 5% Bonus in all your purchases, except AppCoins Credits, in Appcoins Trivial Drive demo sample.",
            "perk_description": "Receive an extra 5% Bonus in all your purchases."
          },
          {
            "id": "PROMO_CODE_PERK",
            "priority": 0,
            "start_date": 1659708015,
            "end_date": 1662909034,
            "current_progress": "0",
            "objective_progress": "0",
            "icon": "https://cdn6.aptoide.com/imgs/6/c/8/6c8dfb1fa8f2c7a6a8fefccf6976274c.png",
            "view_type": "DEFAULT",
            "linked_promotion_id": null,
            "details_link": "https://appcoins-trivial-drive-demo-sample.en.aptoide.com/",
            "app_name": "Appcoins Trivial Drive demo sample",
            "gamification_status": "STANDARD",
            "notification_title": "New Perk",
            "notification_description": "Receive an extra 5% Bonus in all your purchases, except AppCoins Credits, in Appcoins Trivial Drive demo sample.",
            "perk_description": "Receive an extra 5% Bonus in all your purchases."
          }
          ],
          "wallet_origin": "APTOIDE"
        }"""

    val userStatsPromosOrder = """{
  "promotions": [
    {
      "id": "GAMIFICATION",
      "current_amount": 15.43158443,
      "level": 0,
      "bonus": 10.0,
      "next_level_amount": 2000.0,
      "bonus_earned": 1.543158443,
      "status": "ACTIVE",
      "bundle": true,
      "user_type": "UNDEFINED",
      "priority": 100,
      "gamification_status": "STANDARD",
      "approaching_next_level": null
    },
    
    {
      "id": "PACKAGE_DISTRIBUTION_PERK",
      "priority": 0,
      "start_date": ${(System.currentTimeMillis() / 1000) - TimeUnit.DAYS.toSeconds(1)},
      "end_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(2)},
      "current_progress": "0",
      "objective_progress": "0",
      "icon": "https://cdn6.aptoide.com/imgs/3/1/d/31d38eddc037b447a0855e93fb8f1b5e_icon.png",
      "view_type": "DEFAULT",
      "linked_promotion_id": null,
      "details_link": "https://saint-seiya-legend-of-justice-wanda-cinemas-games.en.aptoide.com/",
      "app_name": "1 Saint Seiya: Legend of Justice",
      "gamification_status": "STANDARD",
      "notification_title": "New Perk",
      "notification_description": "Receive an extra 10% Bonus in all your purchases, except AppCoins Credits, in Saint Seiya: Legend of Justice.",
      "perk_description": "Receive an extra 10% Bonus in all your purchases."
    },
    {
      "id": "PACKAGE_DISTRIBUTION_PERK",
      "priority": 10,
      "start_date": ${(System.currentTimeMillis() / 1000) - TimeUnit.DAYS.toSeconds(1)},
      "end_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(2)},
      "current_progress": "0",
      "objective_progress": "0",
      "icon": "https://cdn6.aptoide.com/imgs/7/d/2/7d2971cfd6f9b0bff92ed954a3187d7c_icon.png",
      "view_type": "DEFAULT",
      "linked_promotion_id": null,
      "details_link": "https://super-sus.en.aptoide.com/",
      "app_name": "2 Super Sus -Who Is The Impostor",
      "gamification_status": "VIP",
      "notification_title": "New Perk",
      "notification_description": "Receive an extra 5% Bonus in all your purchases, except AppCoins Credits, in Super Sus -Who Is The Impostor.",
      "perk_description": "Receive an extra 5% Bonus in all your purchases."
    },
    {
      "id": "PACKAGE_DISTRIBUTION_PERK",
      "priority": 0,
      "start_date": ${(System.currentTimeMillis() / 1000) - TimeUnit.DAYS.toSeconds(2)},
      "end_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(4)},
      "current_progress": "0",
      "objective_progress": "0",
      "icon": "https://cdn6.aptoide.com/imgs/5/6/c/56c18ee0dbfd218e4e8c555e9c5ab07a_icon.png",
      "view_type": "DEFAULT",
      "linked_promotion_id": null,
      "details_link": "https://com-wuh-xiaj-aqaer-catap.en.aptoide.com/",
      "app_name": "3 Z Warrior Legend",
      "gamification_status": "STANDARD",
      "notification_title": "New Perk",
      "notification_description": "Receive an extra 10% Bonus in all your purchases, except AppCoins Credits, in Z Warrior Legend.",
      "perk_description": "Receive an extra 10% Bonus in all your purchases."
    },
    {
      "id": "PACKAGE_DISTRIBUTION_PERK",
      "priority": 10,
      "start_date": ${(System.currentTimeMillis() / 1000) - TimeUnit.DAYS.toSeconds(2)},
      "end_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(4)},
      "current_progress": "0",
      "objective_progress": "0",
      "icon": "https://cdn6.aptoide.com/imgs/3/1/d/31d38eddc037b447a0855e93fb8f1b5e_icon.png",
      "view_type": "DEFAULT",
      "linked_promotion_id": null,
      "details_link": "https://saint-seiya-legend-of-justice.en.aptoide.com/",
      "app_name": "4 Saint Seiya: Legend of Justice",
      "gamification_status": "VIP",
      "notification_title": "New Perk",
      "notification_description": "Receive an extra 10% Bonus in all your purchases, except AppCoins Credits, in Saint Seiya: Legend of Justice.",
      "perk_description": "Receive an extra 10% Bonus in all your purchases."
    },
    {
      "id": "PACKAGE_DISTRIBUTION_PERK",
      "priority": 0,
      "start_date": ${(System.currentTimeMillis() / 1000) - TimeUnit.DAYS.toSeconds(1)},
      "end_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(3)},
      "current_progress": "0",
      "objective_progress": "0",
      "icon": "https://cdn6.aptoide.com/imgs/2/1/f/21f345079f05eb23f22a7ea4b5e4a643_icon.png",
      "view_type": "DEFAULT",
      "linked_promotion_id": null,
      "details_link": "https://z-day.en.aptoide.com/",
      "app_name": "5 Z Day: Hearts of Heroes | MMO Strategy War",
      "gamification_status": "STANDARD",
      "notification_title": "New Perk",
      "notification_description": "Receive an extra 5% Bonus in all your purchases, except AppCoins Credits, in Z Day: Hearts of Heroes | MMO Strategy War.",
      "perk_description": "Receive an extra 5% Bonus in all your purchases."
    },
    {
      "id": "PACKAGE_DISTRIBUTION_PERK",
      "priority": 10,
      "start_date": ${(System.currentTimeMillis() / 1000) - TimeUnit.DAYS.toSeconds(1)},
      "end_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(3)},
      "current_progress": "0",
      "objective_progress": "0",
      "icon": "https://cdn6.aptoide.com/imgs/d/a/9/da9bbdcb17a7b26965a68caa60a3f9e6_icon.png",
      "view_type": "DEFAULT",
      "linked_promotion_id": null,
      "details_link": "https://league-of-angels-chaos.en.aptoide.com/",
      "app_name": "6 League of Angels: Chaos",
      "gamification_status": "VIP",
      "notification_title": "New Perk",
      "notification_description": "Receive an extra 10% Bonus in all your purchases, except AppCoins Credits, in League of Angels: Chaos.",
      "perk_description": "Receive an extra 10% Bonus in all your purchases."
    },
    {
      "id": "PACKAGE_DISTRIBUTION_PERK",
      "priority": 0,
      "start_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(1)},
      "end_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(2)},
      "current_progress": "0",
      "objective_progress": "0",
      "icon": "https://cdn6.aptoide.com/imgs/8/0/e/80efa8440e9066ef9237c15c48021d6f_icon.png",
      "view_type": "DEFAULT",
      "linked_promotion_id": null,
      "details_link": "https://com-origem-fadas-catap.en.aptoide.com/",
      "app_name": "7 Poket Contest",
      "gamification_status": "STANDARD",
      "notification_title": "New Perk",
      "notification_description": "Receive an extra 10% Bonus in all your purchases, except AppCoins Credits, in Poket Contest.",
      "perk_description": "Receive an extra 10% Bonus in all your purchases."
    },
    {
      "id": "PACKAGE_DISTRIBUTION_PERK",
      "priority": 10,
      "start_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(1)},
      "end_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(2)},
      "current_progress": "0",
      "objective_progress": "0",
      "icon": "https://cdn6.aptoide.com/imgs/e/e/7/ee76c1067f6754705387f85b660c50ab_icon.jpg",
      "view_type": "DEFAULT",
      "linked_promotion_id": null,
      "details_link": "https://mobile-heroes.en.aptoide.com/",
      "app_name": "8 Mobile Legends: Adventure",
      "gamification_status": "VIP",
      "notification_title": "New Perk",
      "notification_description": "Receive an extra 10% Bonus in all your purchases, except AppCoins Credits, in Mobile Legends: Adventure.",
      "perk_description": "Receive an extra 10% Bonus in all your purchases."
    },
    {
      "id": "PACKAGE_DISTRIBUTION_PERK",
      "priority": 0,
      "start_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(2)},
      "end_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(2)},
      "current_progress": "0",
      "objective_progress": "0",
      "icon": "https://cdn6.aptoide.com/imgs/d/6/f/d6fce756b56a82067301aa017ee7ea52_icon.png",
      "view_type": "DEFAULT",
      "linked_promotion_id": null,
      "details_link": "https://goc-neocraft-limited.en.aptoide.com/",
      "app_name": "9 Guardians of Cloudia",
      "gamification_status": "STANDARD",
      "notification_title": "New Perk",
      "notification_description": "Receive an extra 5% Bonus in all your purchases, except AppCoins Credits, in Guardians of Cloudia.",
      "perk_description": "Receive an extra 5% Bonus in all your purchases."
    },
    {
      "id": "PACKAGE_DISTRIBUTION_PERK",
      "priority": 10,
      "start_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(2)},
      "end_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(2)},
      "current_progress": "0",
      "objective_progress": "0",
      "icon": "https://cdn6.aptoide.com/imgs/d/6/f/d6fce756b56a82067301aa017ee7ea52_icon.png",
      "view_type": "DEFAULT",
      "linked_promotion_id": null,
      "details_link": "https://goc-neocraft-limited.en.aptoide.com/",
      "app_name": "10 Guardians of Cloudia",
      "gamification_status": "VIP",
      "notification_title": "New Perk",
      "notification_description": "Receive an extra 5% Bonus in all your purchases, except AppCoins Credits, in Guardians of Cloudia.",
      "perk_description": "Receive an extra 5% Bonus in all your purchases."
    },
    {
      "id": "PACKAGE_DISTRIBUTION_PERK",
      "priority": 0,
      "start_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(3)},
      "end_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(5)},
      "current_progress": "0",
      "objective_progress": "0",
      "icon": "https://cdn6.aptoide.com/imgs/d/6/f/d6fce756b56a82067301aa017ee7ea52_icon.png",
      "view_type": "DEFAULT",
      "linked_promotion_id": null,
      "details_link": "https://goc-neocraft-limited.en.aptoide.com/",
      "app_name": "11 Guardians of Cloudia",
      "gamification_status": "STANDARD",
      "notification_title": "New Perk",
      "notification_description": "Receive an extra 5% Bonus in all your purchases, except AppCoins Credits, in Guardians of Cloudia.",
      "perk_description": "Receive an extra 5% Bonus in all your purchases."
    },
    {
      "id": "PACKAGE_DISTRIBUTION_PERK",
      "priority": 10,
      "start_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(3)},
      "end_date": ${(System.currentTimeMillis() / 1000) + TimeUnit.DAYS.toSeconds(5)},
      "current_progress": "0",
      "objective_progress": "0",
      "icon": "https://cdn6.aptoide.com/imgs/d/6/f/d6fce756b56a82067301aa017ee7ea52_icon.png",
      "view_type": "DEFAULT",
      "linked_promotion_id": null,
      "details_link": "https://goc-neocraft-limited.en.aptoide.com/",
      "app_name": "12 Guardians of Cloudia",
      "gamification_status": "VIP",
      "notification_title": "New Perk",
      "notification_description": "Receive an extra 5% Bonus in all your purchases, except AppCoins Credits, in Guardians of Cloudia.",
      "perk_description": "Receive an extra 5% Bonus in all your purchases."
    }
  ],
  "wallet_origin": "APTOIDE"
}"""

  }
}