package com.appcoins.wallet.core.utils.properties

object MiscProperties {
  val DEFAULT_TOKEN_SYMBOL =
    if (BuildConfig.DEBUG) ROPSTEN_DEFAULT_TOKEN_SYMBOL else MAIN_NETWORK_DEFAULT_TOKEN_SYMBOL
  val DEFAULT_TOKEN_NAME =
    if (BuildConfig.DEBUG) ROPSTEN_DEFAULT_TOKEN_NAME else MAIN_NETWORK_DEFAULT_TOKEN_NAME
  val DEFAULT_TOKEN_DECIMALS =
    if (BuildConfig.DEBUG) ROPSTEN_DEFAULT_TOKEN_DECIMALS else MAIN_NETWORK_DEFAULT_TOKEN_DECIMALS
  val DEFAULT_TOKEN_ADDRESS =
    if (BuildConfig.DEBUG) ROPSTEN_DEFAULT_TOKEN_ADDRESS else MAIN_NETWORK_DEFAULT_TOKEN_ADDRESS
  val NETWORK_ID = if (BuildConfig.DEBUG) NETWORK_ID_DEV else NETWORK_ID_PROD
  val APTOIDE_PKG_NAME = if (BuildConfig.DEBUG) APTOIDE_PACKAGE_NAME_DEV else APTOIDE_PACKAGE_NAME
  const val PAYMENT_GAS_LIMIT = "125000"
  const val BILLING_SUPPORTED_VERSION = 3
  const val GAMESHUB_PACKAGE = "com.dti.folderlauncher"
  const val GAMESHUB_OEMID = "b61ccfb8fb57721787ecfc2c26c16c6f"
  val ESKILLS_OEM_IDS = listOf<String>("01b4b7f957b2d8ff96a0f742fd5e41fa")
}

private const val ROPSTEN_DEFAULT_TOKEN_SYMBOL = "APPC"
private const val ROPSTEN_DEFAULT_TOKEN_NAME = "AppCoins"
private const val ROPSTEN_DEFAULT_TOKEN_DECIMALS = 18
private const val ROPSTEN_DEFAULT_TOKEN_ADDRESS="0xab949343E6C369C6B17C7ae302c1dEbD4B7B61c3"
private const val MAIN_NETWORK_DEFAULT_TOKEN_SYMBOL = "APPC"
private const val MAIN_NETWORK_DEFAULT_TOKEN_NAME = "AppCoins"
private const val MAIN_NETWORK_DEFAULT_TOKEN_DECIMALS = 18
private const val MAIN_NETWORK_DEFAULT_TOKEN_ADDRESS="0x1a7a8bd9106f2b8d977e08582dc7d24c723ab0db"
private const val NETWORK_ID_PROD = 1
private const val NETWORK_ID_DEV = 3
private const val APTOIDE_PACKAGE_NAME = "cm.aptoide.pt"
private const val APTOIDE_PACKAGE_NAME_DEV = "cm.aptoide.pt.dev"
